name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_run:
    workflows: ["Run tests"]
    types:
      - completed

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
       repository: DragonDev07/Panda-WMI
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Pre-build debug find
      run: find .
    - name: Cache build files
      uses: actions/cache@v3.0.11
      with:
        path: FtcRobotController/build TeamCode/build # A list of files, directories, and wildcard patterns to cache and restore
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }} # An explicit key for restoring and saving the cache
        restore-keys: ${{ runner.os }}-gradle-
    - name: Build with Gradle
      run: ./gradlew build
    - name: Create status
      uses: Sibz/github-status-action@v1.1.6
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        context: 'Android Build'
        description: 'Passed'
        state: 'success'
        sha: ${{github.event.pull_request.head.sha || github.sha}}
